coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 5%
        if_not_found: success
    patch:
      default:
        target: 80%
        threshold: 10%
        if_not_found: success

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false

ignore:
  - "tests/"
  - "**/*.test.ts"
  - "**/*.spec.ts"
  - "**/index.ts"
