/** @type {Partial<import("typedoc").TypeDocOptions>} */
const config = {
  name: 'Validra - Business Rules Engine',
  entryPointStrategy: 'expand',
  entryPoints: ['./src'],
  out: 'docs',
  theme: 'typedoc-github-theme',
  excludeExternals: false,
  exclude: ['**/*+(.spec|.test|.e2e).ts', '**/tests/**/*'],
  navigation: {
    includeCategories: true,
    includeGroups: true,
    excludeReferences: false,
    includeFolders: true,
    compactFolders: true,
  },
  categorizeByGroup: true,
  cleanOutputDir: true,
  customFooterHtml:
    '<p class="tsd-generator">By <a href="https://github.com/Fmanuel809/validra" target="_blank">Validra</a> | MIT License</p>',
  plugin: [
    'typedoc-plugin-dt-links',
    'typedoc-plugin-coverage',
    'typedoc-github-theme',
  ],
  coverageLabel: 'Documentation Coverage',
  coverageOutputType: 'all',
  coverageSvgWidth: 200,
  requiredToBeDocumented: [
    'Enum',
    'EnumMember',
    'Function',
    'Class',
    'Interface',
    'Accessor',
    'TypeAlias',
    'Constructor',
    'Method',
    'Property',
  ],
  validation: {
    invalidLink: true,
    notExported: true,
    notDocumented: true,
    rewrittenLink: true,
    unusedMergeModuleWith: false,
  },
  // Configuración específica para Validra
  readme: './README.md',
  includeVersion: true,
  searchInComments: true,
  sort: ['source-order'],
  kindSortOrder: [
    'Document',
    'Module',
    'Namespace',
    'Enum',
    'EnumMember',
    'Class',
    'Interface',
    'TypeAlias',
    'Constructor',
    'Property',
    'Method',
    'Function',
    'Variable',
  ],
};

export default config;
